#!/usr/bin/env python2
# -*- coding: utf-8 -*-
print"Content-type:text/html\n"
print

print"<pre>"

import cgi
import os
import uuid
import shelve
import pymysql
import time
import sys

donnees=cgi.FieldStorage()

idsess=donnees.getvalue("idsess")
keyword=donnees.getvalue("keyword")
prog=donnees.getvalue("progdef")
t=shelve.open("/tmp/%s.shelf"%idsess)
miningjob_OR_alignjob = t["miningjob_OR_alignjob"]
keyfile = "/tmp/%s.txt"%keyword



if not os.path.isfile(keyfile):
	print"Nous allons telecharger la database"
else:
	print"Database Found"



	
if prog:
	if prog == "SNP":
		choix = "scriptC"
	else:
		choix = "scriptA"
	cmd="""bash %s.bat %s""" %(choix, keyword)	
else :
	cmd="""%s %s""" %(miningjob_OR_alignjob, keyword)

print "je vais lancer la commande : ", cmd
os.system("at now -f job")
os.system(cmd)
# ~ print """
# ~ <script>
# ~ window.location="/TFEwebsite/index.cgi"
# ~ </script>
# ~ """
